# Generated by Django 5.0.6 on 2024-08-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='county',
            new_name='country',
        ),
    ]
